remote_theme: just-the-docs/just-the-docs
title: ProbabiliSaaS Docs
description: ProbabiliSaaS documentation
# logo: "/images/falkor-logo.png"
# favicon_ico: "/images/favicon.ico"
ga_tracking: G-8ELV0F5V4M
ga_tracking_anonymize_ip: true

search_enabled: true
color_scheme: dark

aux_links:
  "Docs Repository":
    - "//github.com/probabilisaas/docs"
#  "FalkorDB Repository":
#    - "//github.com/probabilisaas"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

plugins:
  - jekyll-sitemap

# Navigation structure
collections:
  docs:
    output: true
    permalink: /:path/
    sidebar:
      nav_order: 1
      items:
        - title: "Bloom Filter Commands"
          url: /bf_commands/
          items:
            - title: "Add"
              url: /bf_commands/pbf.add/
            - title: "AddNX"
              url: /bf_commands/pbf.addnx/
            # Add other commands here
        - title: "Cuckoo Filter Commands"
          url: /cf_commands/
          items:
            - title: "Add"
              url: /cf_commands/pcf.add/
            - title: "AddNX"
              url: /cf_commands/pcf.addnx/
            # Add other commands here